app/urls.py
from django.urls import path

from . import views

app_name = 'app' # Redicting pages

urlpatterns = [
    path('', views.index, name='index'),
    path('content', views.content, name='content'),
]

webapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
"""
    This file structure the database:
    1.Launch the make migration in terminal
        'python manage.py makemigrations'
    2.Launch the migrates for all table in application
        'python manage.py migrate'
    3.You can now consult your database in the
      '0001_initial.py' file in the 'migrations' folder
"""
from django.db import models
from django.contrib.contenttypes.fields import (
    GenericForeignKey, GenericRelation
)
from django.contrib.contenttypes.models import ContentType


class Character(models.Model):
    """ Creating the structure the table "Character" for database """
    id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=255, blank=True, null=True)
    species = models.CharField(max_length=255, blank=True, null=True)
    character_type = models.CharField(max_length=255, blank=True, null=True)
    gender = models.CharField(max_length=255, blank=True, null=True)
    origin = models.ForeignKey('Location', on_delete=models.CASCADE, null=True)
    location = models.ForeignKey('Location', on_delete=models.CASCADE,
                                 related_name='characters', null=True)
    image_url = models.URLField(blank=True, null=True)
    episodes = models.ManyToManyField('Episode', related_name='characters')
    url = models.URLField(blank=True, null=True)
    favorite = GenericRelation('Favorite', related_query_name='character')
    created = models.DateTimeField()
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """ Converted the attribute object to string objects"""
        return self.name


class Location(models.Model):
    """
        Creating the structure the table "Location" for database
    """
    id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    location_type = models.CharField(max_length=255, blank=True, null=True)
    dimension = models.CharField(max_length=255, blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    favorite = GenericRelation('Favorite', related_query_name='location')
    created = models.DateTimeField()
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """ Converted the attribute object to string objects"""
        return self.name


class Episode(models.Model):
    """
        Creating the structure the table "Episodes" for database
    """
    # episode_id = The id is auto generate by
    # SQLite associated with a pimaire key
    id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    air_date = models.CharField(max_length=255, blank=True, null=True)
    episode = models.CharField(max_length=255, blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    favorite = GenericRelation('Favorite', related_query_name='episode')
    created = models.DateTimeField()
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """ Converted the attribute object to string objects"""
        return self.name


class Favorite(models.Model):
    """
        Creation of the table "Favorites", to store the
        preferred residents with their rental and type
    """
    favorite_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    favorite_id = models.PositiveIntegerField()
    favorite = GenericForeignKey('favorite_type', 'favorite_id')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.favorite_type}{self.favorite.name}"

    def __str__(self):
        """ Converted the attribute object to string objects"""
        return self.resident

app/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Location, Character

def index(request):
    """ This views return the home page """
    return render(request, "app/index.html")

def content(request):
    """ this views return the application content """
    context = {}
    all_planets = Location.objects.all()
    list_type = set()
    for i in all_planets:
        try:
            list_type.add(i.location_type)
        except:
            pass
    context['planets'] = all_planets
    dict_type_planet = {}
    for i in list_type:
        dict_type_planet[i] = Location.objects.filter(location_type=i)
    context['list_type_planet'] = dict_type_planet
    return render(request, 'app/content.html', context)

app/templates/app/bases.html
<!DOCTYPE html>
<html lang="FR">
	<head>
		<meta charset="UTF-8"/>
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css' %}">
		<title>Rick and Morty Fanatics universes</title>
	</head>

	<body>	

		<header>
			{% block content_header %}
			{% endblock content_header %}
		</header>

			{% block content_body %}
			{% endblock content_body %}

		<footer>
			{% block content_footer %}
			{% endblock content_footer %}
		</footer>

	</body>
</html>

app/templates/app/content.html
{% extends 'app/bases.html' %} <!--inheritance of the html structure-->
{% load static %} <!--Load the static object" css, @font, pictures... "-->


{% block content_header %}
    <!--Display of the header of the html page-->
    <div class="header_home">
        <h4 class="title"><font face="verdana">Rick and Morty Fanatics universes</font></h4>
    </div>
{% endblock content_header %}

{% block content_body %}
    <!--Display of the body of the html page-->
    <p>
        <img src="{% static 'app/pictures/fun_1.png' %}" class="background" alt="Rick and Morty"/>
    </p>

    <div class="body_content">
        <div class="planets">
            <p class="text_appli">
                Choisir une planéte:
            </p>
            <select name="Planets">
                <option selected>Choisissez une planéte dans la liste</option>
                {% for location in planets %}
                <option value="{{ location.name }}">{{ location.name }}</option>
                {% endfor %}
            </select>
        </div>        
    </div>

    <div class="body_content1">
        <div class="type_planet">
            <p class="text_appli">
                Trouver des planétes par son type:
            </p>
            {% for k, v in list_type_planet.items %}
            <h4>{{ k }}</h4>
            <select name="type">
                <option selected>Liste des planetes associé</option>
                {% for planet in v %}
                <option value="1">{{ planet }}</option>
                {% endfor %}
            </select>
            {% endfor %}
        </div>
    </div>


{% endblock content_body %}

{% block content_footer %}
    <!--Display of the foot of the html page-->
    <div class="footer_home">
        <h5>.: Created by | Lyss | Sulyvan Dercourt Concéption/Montage  HTML5 | CSS3 2019 © :.</h5>
    </div>
{% endblock content_footer %}

app/templates/app/index.html
{% extends 'app/bases.html' %} <!--inheritance of the html structure-->
{% load static %} <!--Load the static object" css, @font, pictures... "-->

{% block content_header %}
    <!--Display of the header of the html page-->
    <div class="header_home">
        <h4 class="title"><font face="verdana">Rick and Morty Fanatics universes</font></h4>
    </div>
{% endblock content_header %}

{% block content_body %}
    <!--Display of the body of the html page-->
    <p>
        <img src="{% static 'app/pictures/fun_2.png' %}" class="background" alt="Rick and Morty"/>
    </p>
    <div class="body_home">
        <a href="{% url 'app:content' %}">
            <p class='link'>
                - En construction -</br>
                - Consulter les planètes -
            </p>
        </a>
        <a class="git_hub" href="https://github.com/Lyss74/AboutsGoodsApp">
            - Consulter le Git hub -
        </a>
    </div>

{% endblock content_body %}

{% block content_footer %}
    <!--Display of the foot of the html page-->
    <div class="footer_home">
        <h5>.: Created by | Lyss | Sulyvan Dercourt Concéption/Montage  HTML5 | CSS3 2019 © :.</h5>
    </div>
{% endblock content_footer %}